### ISSUE TITLE
Facebook integration

### ISSUE THREAD

**Issue by miromarchi** [retebuonvivere/retebuonvivere#8]
This issue is the base for general discussion about facebook integration.
# What we need
## Groupwise:
- [ ] Importing fb pages info (description, address, ...) and map them to specific rbv fields → issue #6 
- [ ] Importing fb events into rbv events → issue #6
- [ ] Show fb "page plugin" on rbv nodes connected to fb pages → issue #47
- [ ] Publish new completed content on facebook (e.g. publish a rbv event as fb event)
## Sitewise:
- [ ] User login with fb account → issue #7 
- [ ] Publish new completed content on rbv's own fb page → issue #43 
## Developing suggestions

We created a fb App named retebuonvivere with app id 1375538096079292

Ideally all the features should work together as a whole, in a modular way!
## Documentation

One can start from:
[Resource guide: social media and drupal](https://www.drupal.org/resource-guides/social-media-and-drupal)
##
